### ISSUE TITLE
[Bug]: Upgrading from 1.20.1 to 1.20.4 breaks the world

### ISSUE THREAD

**Issue by rGunti** [KonoTyran/Minecraft_AP_Randomizer#33]
### What happened?

Today I started the game server and it suggested to update, which I did. After connecting to the server, I was again spawned in the glass room with a jumbled inventory. When entering `/start` in the chat, I was spawned into the world normally, but I found odd items lying around. When I looked at my base, everything was messed up (see picture attached). Also when trying to place one block, it switched to a different one. I got stuck on what were path blocks.

I then loaded the save game in Single Player, where everything seemed normal.

Broken:
![image](https://github.com/user-attachments/assets/e2c243b3-24af-4910-b0c7-c8ae5e56b08a)

How it should look like:
![image](https://github.com/user-attachments/assets/d063b212-d123-4a97-a49a-3b274b86ffd5)

### Manual Minecraft Launch?

- [ ] Manual Launch

### Version

Minecraft Server (Default)

**Comment by KonoTyran** [comment]
This is known, and there is really not much I can do about it, the release post on Discord mentions this. Best i can tell this is an issue with forge, which is why this version is going to be retired and replaced with a fabric version. To fix this for now you can change `release_channel` in your `host.yaml` to `old`
